-- MySQL Script generated by MySQL Workbench
-- 06/19/24 00:07:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema avaliacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema avaliacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avaliacao` DEFAULT CHARACTER SET utf8 ;
USE `avaliacao` ;

-- -----------------------------------------------------
-- Table `avaliacao`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`aluno` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliacao`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`materia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliacao`.`assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`assunto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `id_materia` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_assunto_questao_idx` (`id_materia` ASC),
  CONSTRAINT `fk_assunto_questao`
    FOREIGN KEY (`id_materia`)
    REFERENCES `avaliacao`.`materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliacao`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`professor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliacao`.`tipo_de_questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`tipo_de_questao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliacao`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`questao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `enunciado` VARCHAR(300) NOT NULL,
  `resposta_correta` VARCHAR(100) NOT NULL,
  `resposta_errada1` VARCHAR(100) NOT NULL,
  `resposta_errada2` VARCHAR(100) NOT NULL,
  `resposta_errada3` VARCHAR(100) NOT NULL,
  `dificuldade` INT(11) NOT NULL,
  `id_materia` INT(11) NOT NULL,
  `id_assunto` INT(11) NOT NULL,
  `id_tipo` INT(11) NOT NULL,
  `id_professor` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_questao` (`id_materia` ASC),
  INDEX `fk_questao_assunto_idx` (`id_assunto` ASC),
  INDEX `fk_questao_tipo_idx` (`id_tipo` ASC),
  INDEX `index_professor` (`id_professor` ASC),
  CONSTRAINT `fk_questao_assunto`
    FOREIGN KEY (`id_assunto`)
    REFERENCES `avaliacao`.`assunto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questao_materia`
    FOREIGN KEY (`id_materia`)
    REFERENCES `avaliacao`.`materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questao_professor`
    FOREIGN KEY (`id_professor`)
    REFERENCES `avaliacao`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questao_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `avaliacao`.`tipo_de_questao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliacao`.`historico_de_questoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`historico_de_questoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_questao` INT(11) NOT NULL,
  `correta` TINYINT(1) NOT NULL,
  `timestamp` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historico_questoes_idx` (`id_questao` ASC),
  CONSTRAINT `fk_historico_questoes`
    FOREIGN KEY (`id_questao`)
    REFERENCES `avaliacao`.`questao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliacao`.`prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`prova` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `data_criacao` DATE NOT NULL,
  `id_professor` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prova_questao_idx` (`id_professor` ASC),
  CONSTRAINT `fk_prova_questao`
    FOREIGN KEY (`id_professor`)
    REFERENCES `avaliacao`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliacao`.`questao_da_prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`questao_da_prova` (
  `id_prova` INT(11) NOT NULL AUTO_INCREMENT,
  `id_questao` INT(11) NOT NULL,
  `valor` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`id_prova`),
  INDEX `fk_questaoProva_questao_idx` (`id_questao` ASC),
  CONSTRAINT `fk_questaoProva_prova`
    FOREIGN KEY (`id_prova`)
    REFERENCES `avaliacao`.`prova` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questaoProva_questao`
    FOREIGN KEY (`id_questao`)
    REFERENCES `avaliacao`.`questao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `avaliacao`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avaliacao`.`resposta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_prova` INT(11) NOT NULL,
  `id_aluno` INT(11) NOT NULL,
  `id_questao` INT(11) NOT NULL,
  `resposta` VARCHAR(100) NOT NULL,
  `correta` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resposta_questao_idx` (`id_questao` ASC),
  INDEX `fk_resposta_prova_idx` (`id_prova` ASC),
  INDEX `fk_resposta_aluno_idx` (`id_aluno` ASC),
  CONSTRAINT `fk_resposta_aluno`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `avaliacao`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resposta_prova`
    FOREIGN KEY (`id_prova`)
    REFERENCES `avaliacao`.`prova` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resposta_questao`
    FOREIGN KEY (`id_questao`)
    REFERENCES `avaliacao`.`questao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


